name       : python-apsw
version    : 3.24.0_1
release    : 8
source     :
    - https://github.com/rogerbinns/apsw/archive/3.24.0-r1.tar.gz : d9769daba2112aec7f46b807097818f68f03a9aaac61dd1e4bb0cc4167f8d29d
license    : Zlib
component  : programming.python
summary    : Another Python SQLite Wrapper
description: |
    APSW is a Python wrapper for the SQLite embedded relational database
    engine. In contrast to other wrappers such as pysqlite it focuses on
    being a minimal layer over SQLite attempting just to translate the
    complete SQLite API into Python.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
