name       : python-apsw
version    : 3.41.2.0
release    : 16
source     :
    - https://github.com/rogerbinns/apsw/archive/refs/tags/3.41.2.0.tar.gz : 03d4e1995a561b8ff2c5c07534fb6c93b2971994157ccd44df21e8bc7df0e139
homepage   : https://github.com/rogerbinns/apsw
license    : Zlib
component  : programming.python
summary    : Another Python SQLite Wrapper
description: |
    APSW is a Python wrapper for the SQLite embedded relational database engine. In contrast to other wrappers such as pysqlite it focuses on being a minimal layer over SQLite attempting just to translate the complete SQLite API into Python.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
build      : |
    %python3_setup --enable=load_extension
install    : |
    %python3_install
check      : |
    %python3_test
