name       : python-apsw
version    : 3.29.0
release    : 11
source     :
    - https://github.com/rogerbinns/apsw/archive/3.29.0-r1.tar.gz : a5715b4ff614d6bc3b19dcd73e54d5ba0c5340cdae6141ef6dd1e09b289bf7f7
license    : Zlib
component  : programming.python
summary    : Another Python SQLite Wrapper
description: |
    APSW is a Python wrapper for the SQLite embedded relational database engine. In contrast to other wrappers such as pysqlite it focuses on being a minimal layer over SQLite attempting just to translate the complete SQLite API into Python.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # https://github.com/rogerbinns/apsw/issues/275
    #python3_test
