name       : python-apsw
version    : 3.8.5.1
release    : 1
source     :
    - https://pypi.python.org/packages/source/a/apsw/apsw-3.8.5-r1.tar.gz : 3d1ddccdd3f61765b4a98599e7f5c7ed3b7da74ebce955513d6e14db9bd07ece
license    :
    - Zlib
    - Libpng
summary    : Another Python SQLite Wrapper
description: |
    A Python wrapper for the SQLite embedded relational database engine.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.4)
    - pkgconfig(sqlite3)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
