name       : python-apsw
version    : 3.22.0.1
release    : 7
source     :
    - https://github.com/rogerbinns/apsw/releases/download/3.22.0-r1/apsw-3.22.0-r1.zip : 8ab4cf7922cfe98b234110891b33bbb9f6f33f8762967905fa8a7a43bc2a9d71
license    : Zlib
component  : programming.python
summary    : Another Python SQLite Wrapper
description: |
    APSW is a Python wrapper for the SQLite embedded relational database
    engine. In contrast to other wrappers such as pysqlite it focuses on
    being a minimal layer over SQLite attempting just to translate the
    complete SQLite API into Python.
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        PYTHONPATH=$installdir/usr/lib/python2.7/site-packages python setup.py test
    popd

    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$installdir/usr/lib/python3.6/site-packages python3 setup.py test
    popd
